- name: Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: Disable Nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Disable Nodejs
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install Nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Copy service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Adding expense user
      ansible.builtin.user:
        name: expense

    - name: Remove old content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Creating App dir
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and Extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Download Nodejs dependencies
      community.general.npm:
        path: /app
        state: latest

#    - name: Install Python MySQL Client
#      ansible.builtin.pip:
#        name:
#          - PyMySQL
#          - cryptography
#        executable: pip3.9
    - name: install mysql client
      ansible.builtin.dnf:
       name: mysql
       state: installed

    - name: Load Schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.mohdshuja.com

    - name: Start Backend
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enabled: yes
        daemon_reload: yes
